'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function TeamAccess(){
 const [members,setMembers]=useState<{email:string}[]>([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[reset,setReset]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[removing,setRemoving]=useState('');
 async function request(body?:unknown){const r=await fetch('/api/team',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json() as {error?:string;members?:{email:string}[]};if(!r.ok)throw Error(j.error||'Could not update team.');return j;}
 async function load(){try{setMembers((await request()).members||[]);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{await request({action:reset?'reset':'add',email,password});setMessage(reset?'Password updated. Previous sessions are signed out.':'Member added. Share the dashboard link and password with them privately.');setPassword('');setEmail('');setReset(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);setError('');try{await request({action:'remove',email:removing});setRemoving('');setMessage('Member removed. Their access has ended.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="team-access"><p>Members can view all accounts, edit client names, and add or remove Meta connections. Only you can manage team access.</p>{error&&<p role="alert" className="red">{error}</p>}{message&&<p role="status">{message}</p>}<ul className="team-list">{members.map(m=><li key={m.email}><span>{m.email}<small>Editor</small></span><Button variant="outline" disabled={busy} onClick={()=>{setEmail(m.email);setPassword('');setReset(true);setMessage('');}}>Reset password</Button><Button variant="outline" disabled={busy} onClick={()=>setRemoving(m.email)}>Remove</Button></li>)}</ul>{!members.length&&<p className="muted">No members added yet.</p>}{removing&&<div className="team-confirm"><p>Remove access for {removing}?</p><Button disabled={busy} onClick={remove}>Remove member</Button> <Button variant="outline" onClick={()=>setRemoving('')}>Cancel</Button></div>}<form className="login-form" onSubmit={submit}><h2>{reset?'Reset member password':'Add team member'}</h2><label htmlFor="member-email">Member email</label><Input id="member-email" type="email" autoComplete="off" required readOnly={reset} value={email} maxLength={254} onChange={e=>setEmail(e.target.value)}/><label htmlFor="member-password">{reset?'New password':'Dashboard password'}</label><Input id="member-password" type="password" autoComplete="new-password" required minLength={16} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/><p className="muted">At least 16 characters. Share it with this member privately. No email is sent automatically.</p><Button disabled={busy} type="submit">{busy?'Saving…':reset?'Save new password':'Add member'}</Button>{reset&&<Button variant="outline" type="button" onClick={()=>{setReset(false);setEmail('');setPassword('');}}>Cancel reset</Button>}</form><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin);setMessage('Dashboard link copied.');}catch{setError('Could not copy the link.');}}}>Copy dashboard link</Button></div>;
}
